language: node_js
node_js:
  - "node"
  - "0.10"
  - "0.11.13"

  # v0.11.14 changed ReadableStream.prototype.resume. Also introduced writing
  # binary strings.
  - "0.11.14"
  - "0.11"
  - "0.12"
  - "4"
  - "5"
  - "6.0"
  - "6.3"

  # v6.4 introduced writing latin1 strings.
  - "6.4"
  - "6"

  # v7 changed the internal _normalizeConnectArgs's function name.
  - "7"
  - "8.11"

  # v8.12 revamped parts of HTTP parsing.
  - "8.12"
  - "8"
  - "9.5"

  # v9.6 revamped parts of HTTP parsing just like v8.12.
  - "9.6"
  - "9"
  - "10.0.0"
  - "10"
  - "11.0"

  # v11.1 changed onStreamRead in stream_base_commons.js to get the byte count
  # through a global structure.
  - "11.1"

  # v11.2 requires InternalSocket.prototype.shutdown.
  - "11.2"
  - "11"

  # IO.js required TlsSocket.prototype.getSession.
  - "iojs"
  - "iojs-v2.4.0"
  - "iojs-v3.2.0"

notifications:
  email: ["andri@dot.ee"]
